import type { AuditReport } from "@/types";

export const demoReport: AuditReport = {
  id: "demo",
  createdAt: new Date().toISOString(),
  listing: {
    platform: "android",
    appId: "com.vasu.secret.vault.calculator",
    title: "Private Vault – Hide Photos",
    developer: "Vasu Apps",
    iconUrl:
      "https://play-lh.googleusercontent.com/iK9S6tYIinESIlopDUUs71VNfTuwDTUYCvMYQgyvitKhiqmN47YAW8A2h5RjzUSmX9onhUj3U8Mfsw9gXyvZ",
    screenshots: [
      "https://play-lh.googleusercontent.com/5Dh2pKLmJkndqIfwEPIOZursfQqrXKbCi_szmeFR-SdXYsbvwRujQZlhKgKtyCCnopXuT-nCKx5xcykGnMGx",
      "https://play-lh.googleusercontent.com/elaiqrDX0ypeceGjkRMAY4EnM30RN3tixFIWlVMdeQblSAjTqd-B4QrFrOC6e9JHB8MCDSotGniuEqh-ue4x",
      "https://play-lh.googleusercontent.com/OJb11cRplLwV75z7wWjMDopHeQPwQQaMnuRNPe5maMFbVoOna3p8BhtwLxEUgQTgVHcFYq29MNQ8OgP2yKiz",
      "https://play-lh.googleusercontent.com/tafgGO0jujQCV2bP_XiFhbdREYwHV8aSF9ghFVDY94lER2wVums18DiGduiwPCZTrsnA50vdNiBhqBdlTltUyA",
      "https://play-lh.googleusercontent.com/AiBy6JmVUCgmsm_zXZ_0fibIzRDpTQfK4elNHDNyCEc_sF-s5gI2exXMNzb8cK4Cxf3vNUO1EpiGBPko_A6Ojg",
      "https://play-lh.googleusercontent.com/nQDmgjR3ILiSThbRi0K2cbub7YvHK-JdG7wtOFWqIMyp304N5oYjiL-2WA9bJ6-6n7BSVRHDhiPadC6WT6Qw-Q",
    ],
    featuredGraphic:
      "https://play-lh.googleusercontent.com/uJ1S3pipkMV4dYOrJar5BFUvi71b2_GygErzSm5_aiMn0YFEbORVq_jfZICjl9Wto35-wx72gENzTZD32MqX",
    subtitle: "Hide photos & videos securely. Private browser, notes, and PIN lock vault.",
    description:
      "Private Vault – Hide Photos is a secure privacy app that helps you hide photos, hide videos, and protect private content on your phone with a PIN lock vault.\n\nIf you want to keep personal images, videos, notes, or browsing activity private, this app provides a simple and reliable solution. Your hidden files stay inside a private vault that only you can access.\n\n• Hide Photos & Videos Securely\n  Hide photos and videos from your gallery. Keep private media inside a secure vault. Easy import and restore anytime.\n\n• PIN Lock & Security Protection\n  Protect your vault with a PIN lock. Set a security password for access. Forgot PIN option available for recovery.\n\n• Private Browser\n  Browse websites privately inside the app. No browsing history saved. Protect your privacy while surfing.\n\n• Private Notes\n  Create and store private notes securely. Protect important information with a lock.\n\nWhy Private Vault? Hide photos, videos, and notes easily. Secure PIN lock protection. Built-in private browser. Clean and simple interface. Designed for privacy-focused users.",
    rating: 4.5,
    reviews: 4820,
    installs: "500,000+",
    category: "Tools",
    updated: "2026-06-02T12:48:03.000Z",
    version: "1.3.5",
    storeUrl:
      "https://play.google.com/store/apps/details?id=com.vasu.secret.vault.calculator&hl=en_IN",
  },
  audit: {
    score: 5.8,
    scoreLabel: "Needs Work",
    potentialGain: 2.4,
    summary:
      "Private Vault has clear privacy positioning but the screenshot sequence is weak for conversion: frame 1 is a text feature list instead of real UI, frame 2 buries the app inside a decorative phone mockup, frame 3 shows failed Face ID (undermining trust), frame 4 is an empty notification popup, the icon is too intricate for small sizes, and the featured graphic is visually cluttered. Tightening every frame to show real app UI with clear benefit hooks could meaningfully improve conversion.",
    issues: [
      {
        id: "issue_1",
        severity: "High",
        assetType: "Screenshot",
        assetIndex: 1,
        title: "First screenshot is a feature list, not the actual app UI",
        whyItMatters:
          "The opening frame lists features ('Hide Photos, Videos, Files & More') as text on a pastel blue background instead of showing the real app interface. Users scanning the gallery in under 3 seconds can't visualise what the app looks like, which delays the install decision.",
        fix: "Replace with a real app interface screenshot — show the vault's home screen with files visible and a clear 'locked' indicator. Let the product speak, not a bullet list.",
        impactGain: 0.8,
        priority: 1,
        coordinates: { x: 0.05, y: 0.18, width: 0.9, height: 0.25 },
        userBehaviorImpact: "Understanding",
        conversionStage: "Screenshot Gallery",
        abTestIdea: "A/B test current feature-list screenshot vs actual vault home screen",
        confidence: "High",
      },
      {
        id: "issue_2",
        severity: "High",
        assetType: "Screenshot",
        assetIndex: 2,
        title: "Promotional phone mockup buries the actual UI at thumbnail size",
        whyItMatters:
          "The second frame shows an iPhone mockup with a passcode screen, but the phone is small within the frame and surrounded by generic couple photos. At search-grid size the detail is invisible, wasting the slot.",
        fix: "Remove the decorative photos, zoom in so the passcode screen fills the frame. Add a short text overlay like 'PIN-protected vault' so the benefit reads even at small size.",
        impactGain: 0.5,
        priority: 2,
        coordinates: { x: 0.1, y: 0.05, width: 0.8, height: 0.55 },
        userBehaviorImpact: "Readability",
        conversionStage: "Search Result",
        abTestIdea: "Test full-frame UI screenshot vs current mockup-with-decoration version",
        confidence: "High",
      },
      {
        id: "issue_6",
        severity: "Medium",
        assetType: "Screenshot",
        assetIndex: 3,
        title: "Lock screen shows failed Face ID attempts — undermines trust",
        whyItMatters:
          "The Face ID/Touch ID/PIN screen displays 'failed face recognition' which signals the app doesn't work reliably. Users evaluating a security tool may question its dependability.",
        fix: "Show a successful unlock state instead. A green 'Face ID matched' or an unlocked vault home builds confidence. Never show error states in conversion imagery.",
        impactGain: 0.45,
        priority: 3,
        coordinates: { x: 0.15, y: 0.08, width: 0.7, height: 0.2 },
        userBehaviorImpact: "Trust",
        conversionStage: "Screenshot Gallery",
        abTestIdea: "Test 'Face ID failed' vs 'Face ID matched' lock screen variants",
        confidence: "High",
      },
      {
        id: "issue_7",
        severity: "Medium",
        assetType: "Screenshot",
        assetIndex: 4,
        title: "Notification-only screenshot shows no app interface",
        whyItMatters:
          "The fourth frame is just a system notification popup reading 'Your Memories. Fully Protected.' — there's zero app UI shown. This feels like an empty placeholder and doesn't help a user evaluate the product.",
        fix: "Show the album/gallery view inside the vault with a few photos visibly locked. The notification could appear as a small overlay, not the main subject.",
        impactGain: 0.35,
        priority: 4,
        coordinates: { x: 0.1, y: 0.1, width: 0.8, height: 0.25 },
        userBehaviorImpact: "Relevance",
        conversionStage: "Screenshot Gallery",
        abTestIdea: "Test notification-only frame vs vault gallery view with lock indicators",
        confidence: "High",
      },
      {
        id: "issue_3",
        severity: "Medium",
        assetType: "Icon",
        assetIndex: null,
        title: "Icon is too complex — sunset + padlock is hard to read at small sizes",
        whyItMatters:
          "The icon depicts a sunset over water with a padlock overlay. The imagery is intricate and hard to distinguish at 48×48px. Users scanning search results won't immediately connect this to a privacy vault app.",
        fix: "Simplify to a single strong symbol — a shield with a checkmark or a solid lock on a clean background. Lose the landscape detail.",
        impactGain: 0.4,
        priority: 5,
        coordinates: null,
        userBehaviorImpact: "Relevance",
        conversionStage: "Search Result",
        abTestIdea: "A/B test current icon vs simplified shield/lock icon in Google Play experiments",
        confidence: "Medium",
      },
      {
        id: "issue_4",
        severity: "Medium",
        assetType: "Description",
        assetIndex: null,
        title: "Description buries trust-building content below feature list",
        whyItMatters:
          "The '500K+ installs' and security guarantees appear deep in the description. Most users never expand past the first 3 lines, so they miss the strongest trust signals.",
        fix: "Move the install count and a security promise into the first 2 visible lines. Open with: 'Trusted by 500K+ users to hide photos & videos safely.'",
        impactGain: 0.4,
        priority: 6,
        coordinates: null,
        userBehaviorImpact: "Trust",
        conversionStage: "Product Page Scan",
        abTestIdea: "Test benefit-first opening vs current feature-first opening",
        confidence: "High",
      },
      {
        id: "issue_5",
        severity: "Low",
        assetType: "Featured Graphic",
        assetIndex: null,
        title: "Featured graphic is cluttered with too many elements",
        whyItMatters:
          "The banner uses a diamond-pattern background, a phone image, multiple lock icons, and small text labels ('Secret', 'Easy'). At listing size this visual noise reduces the impact of the core message.",
        fix: "Simplify to a single strong visual — one phone with a lock badge and a short 3-word headline like 'Your Private Vault'. Remove the pattern background.",
        impactGain: 0.3,
        priority: 7,
        coordinates: null,
        userBehaviorImpact: "Understanding",
        conversionStage: "Impression",
        abTestIdea: "Test simplified single-focus banner vs current cluttered version",
        confidence: "Medium",
      },
      {
        id: "issue_8",
        severity: "Low",
        assetType: "Screenshot",
        assetIndex: 5,
        title: "File storage UI is cluttered — too many action elements per screen",
        whyItMatters:
          "The file list shows documents with lock/unlock buttons, a PIN entry overlay, and gradient/shadows that add visual noise. At store thumbnail size the hierarchy collapses into a busy blur.",
        fix: "Show one file being unlocked with a clean lock icon overlay. Remove gradients and shadows — flatter UI reads better at small sizes. Use a single clear CTA per frame.",
        impactGain: 0.2,
        priority: 8,
        coordinates: { x: 0.05, y: 0.45, width: 0.9, height: 0.35 },
        userBehaviorImpact: "Readability",
        conversionStage: "Search Result",
        abTestIdea: "Test simplified single-file unlock view vs full file list",
        confidence: "Low",
      },
      {
        id: "issue_9",
        severity: "Low",
        assetType: "Screenshot",
        assetIndex: 6,
        title: "Cartoon detective character feels unprofessional for a security app",
        whyItMatters:
          "The final frame shows a cartoon detective with a mask and hat to represent private browsing. This playful illustration undermines the serious security tone that privacy-conscious users expect from a vault app.",
        fix: "Replace the cartoon with a clean privacy icon (shield, eye with slash, or incognito silhouette). Keep the 'Clear History' checkboxes but present them in a more polished, professional layout.",
        impactGain: 0.2,
        priority: 9,
        coordinates: { x: 0.2, y: 0.04, width: 0.6, height: 0.3 },
        userBehaviorImpact: "Trust",
        conversionStage: "Install Decision",
        abTestIdea: "Test cartoon detective vs clean privacy icon variant",
        confidence: "Medium",
      },
    ],
    assetsHealth: {
      icon: {
        status: "Needs Work",
        score: 56,
        summary:
          "The sunset-over-water imagery with a padlock is too intricate for small sizes. Users may not connect this to a privacy vault app at a glance in search results.",
        improvements: ["Simplify to a single strong symbol (shield or solid lock)", "Test icon variants for readability at 48×48px"],
      },
      screenshots: {
        status: "Weak",
        score: 42,
        summary:
          "Of the 6 screenshots, only the file storage (shot 5) and private browser (shot 6) show real app UI. Shot 1 is a text feature list, shot 2 is a decorative phone mockup, shot 3 shows a failed Face ID state, and shot 4 is just a notification popup. The sequence doesn't build trust or show the product experience.",
        improvements: [
          "Replace feature-list screenshot with vault home screen",
          "Remove decorative phone mockup — show UI full-frame",
          "Show successful Face ID instead of failed state",
          "Replace notification-only frame with gallery view",
          "Simplify file storage UI for thumbnail readability",
          "Replace cartoon detective with professional privacy icon",
        ],
      },
      featuredGraphic: {
        status: "Needs Work",
        score: 52,
        summary:
          "Too many elements compete for attention — diamond pattern background, phone mockup, multiple lock icons, text labels. The core message is lost in the clutter.",
        improvements: ["Simplify to one phone + one lock badge", "Replace pattern background with solid colour", "Use a 3-word headline max"],
      },
      title: {
        status: "Strong",
        score: 82,
        summary:
          "Clear, keyword-rich, and communicates both the function (vault) and the value (hide photos). Well within Play Store length limits.",
        improvements: ["Keep 'Private Vault' primary for brand recall"],
      },
      description: {
        status: "Needs Work",
        score: 58,
        summary:
          "Thorough feature coverage but the critical trust and social proof signals are buried below the fold.",
        improvements: [
          "Open with a trust statement (install count, security promise)",
          "Shorten bullets for faster scanning",
        ],
      },
      overall: {
        status: "Needs Work",
        score: 52,
        summary:
          "Clear privacy positioning with strong keyword alignment, but the screenshot sequence is the weakest link — most frames don't show real app UI, and the few that do have readability or trust issues.",
        improvements: [
          "Replace 4 of 6 screenshots with actual app UI frames",
          "Simplify icon for small-size recognition",
          "Surface install count earlier in description",
        ],
      },
    },
    workingWell: [
      {
        assetType: "Title",
        title: "Strong keyword alignment",
        description: "'Private Vault – Hide Photos' clearly communicates the app's purpose and matches search intent for privacy tools.",
      },
      {
        assetType: "Screenshot",
        title: "Private browser screen shows clear functionality",
        description: "The 'Clear History' checkboxes and privacy mode description in screenshot 6 communicate a useful feature, despite the cartoon styling.",
      },
      {
        assetType: "Overall",
        title: "Clear privacy value proposition",
        description: "The listing consistently positions itself as a privacy solution, which aligns with the target audience's primary concern.",
      },
    ],
    textAudit: {
      title: {
        length: 30,
        feedback: "Clear and keyword-optimised. 'Private Vault' establishes brand while 'Hide Photos' captures search intent.",
        suggestions: ["No changes needed — title is well optimised"],
      },
      shortDescription: {
        length: 72,
        feedback: "Covers all key features but could be more outcome-driven. 'Hide photos & videos securely' is strong, but 'PIN lock vault' is a feature, not a benefit.",
        suggestions: ["Lead with 'Keep your photos & videos private'"],
      },
      description: {
        length: null,
        feedback: "Comprehensive feature list but the first visible lines should build trust, not just list features. The '500K+ installs' stat is a powerful trust signal that appears too late.",
        suggestions: [
          "Open with install count + security promise",
          "Reduce bullet length for faster scanning",
          "Add a specific security guarantee (e.g., 'Files never leave your device')",
        ],
      },
    },
    actionPlan: [
      {
        priority: 1,
        task: "Replace feature-list screenshot 1 with actual vault home screen UI",
        impact: "High",
        effort: "Medium",
        expectedGain: 0.8,
      },
      {
        priority: 2,
        task: "Remove decorative phone mockup from screenshot 2 — show UI full-frame",
        impact: "High",
        effort: "Low",
        expectedGain: 0.5,
      },
      {
        priority: 3,
        task: "Replace failed Face ID state with successful unlock on screenshot 3",
        impact: "Medium",
        effort: "Low",
        expectedGain: 0.45,
      },
      {
        priority: 4,
        task: "Replace notification-only screenshot 4 with vault gallery view",
        impact: "Medium",
        effort: "Medium",
        expectedGain: 0.35,
      },
      {
        priority: 5,
        task: "Simplify icon to a single recognisable shield or lock symbol",
        impact: "Medium",
        effort: "Medium",
        expectedGain: 0.4,
      },
      {
        priority: 6,
        task: "Rewrite description opening to lead with trust + install count",
        impact: "Medium",
        effort: "Low",
        expectedGain: 0.4,
      },
      {
        priority: 7,
        task: "Simplify featured graphic — remove pattern background, reduce elements",
        impact: "Low",
        effort: "Low",
        expectedGain: 0.3,
      },
      {
        priority: 8,
        task: "Simplify file storage UI for thumbnail readability in screenshot 5",
        impact: "Low",
        effort: "Low",
        expectedGain: 0.2,
      },
      {
        priority: 9,
        task: "Replace cartoon detective with professional privacy icon in screenshot 6",
        impact: "Low",
        effort: "Low",
        expectedGain: 0.2,
      },
    ],
  },
};
