import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Use — AppLens AI",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-5 py-16 sm:px-8 sm:py-24">
        <Link href="/" className="mb-8 inline-flex items-center gap-1.5 text-sm font-semibold text-foreground/50 transition-colors hover:text-foreground">
          <ArrowLeft className="h-4 w-4" /> Back to home
        </Link>
        <h1 className="font-display text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Terms of Use</h1>
        <p className="mt-2 text-sm text-foreground/45">Last updated: June 2026</p>

        <div className="mt-10 space-y-6 text-base leading-8 text-foreground/78">
          <section>
            <h2 className="mb-2 font-display text-xl font-extrabold tracking-[-0.04em] text-foreground">Use of Service</h2>
            <p>
              AppLens AI provides an automated tool for analyzing publicly available app store listings. By using this service, you agree to these terms. The service is provided free of charge and is intended for informational and educational purposes.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-display text-xl font-extrabold tracking-[-0.04em] text-foreground">No Guarantee of Accuracy</h2>
            <p>
              Audit results are generated by an AI model and may contain errors or inaccuracies. The analysis should be used as a reference and not as the sole basis for business decisions. We make no guarantees about the completeness, reliability, or accuracy of audit reports.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-display text-xl font-extrabold tracking-[-0.04em] text-foreground">Acceptable Use</h2>
            <p>
              You agree to use this service only for lawful purposes and in accordance with these terms. You may not use the service to submit malicious URLs, scrape the service, or interfere with its operation.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-display text-xl font-extrabold tracking-[-0.04em] text-foreground">Intellectual Property</h2>
            <p>
              AppLens AI and the audit reports generated by the service are provided as-is. The app store listing content analyzed by the tool remains the property of the respective app developers and store platforms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-display text-xl font-extrabold tracking-[-0.04em] text-foreground">Limitation of Liability</h2>
            <p>
              AppLens AI and its creators are not liable for any damages or losses arising from the use or inability to use the service, including but not limited to decisions made based on audit results.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-display text-xl font-extrabold tracking-[-0.04em] text-foreground">Changes to Terms</h2>
            <p>
              We reserve the right to update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
